spring:
  datasource:
    url: jdbc:mysql://114.55.93.200:3306/blog?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 114.55.93.200
    port: 6379

  mvc:
    servlet:
      path: /api #路径带上api


server:
  port: 8080
